[package]
name = "project_rnd"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
artem = "3.0.0"
image = { version = "0.25.6", default-features = false, features = ["jpeg"] }
ratatui = "0.29.0"
crossterm = "0.29.0"

[lints.clippy]
needless_return = "allow"
